const BaseURL = "https://api-staging.aliflaila.app/api/";
// const BaseURL = "https://api.aliflaila.app/api/";
const GoogleAPI =
  "101322409355-an159kr072h5k01ro4va39g0phv98ooe.apps.googleusercontent.com";
const FacebookAppId = "624397796432943";
// const ProxyURL = "https://proxy.codingpixel.org/";
const ProxyURL = "https://cors-proxy-production-761e.up.railway.app/";

const Endpoint = {
  auth: {
    login: "login",
    logout: "logout",
    register: "signup",
    sendEmailOtp: "send-email-otp",
    verifyEmailOtp: "verify-email-otp",
    resetPassword: "reset-password",
    checkEmail: "check-email",
    socialLogin: "social-login",
    socialRegister: "social-register",
  },
  partner: {
    dashboard: {
      getDashboardStats: "/stats/dashboard",
      getMostReadGenres: "/stats/popular-genres",
      getBooksStats: "/stats/books",
      graph: "/stats/graph/sales",
    },
    chat: {
      getRoomId: "/chat/get-room",
      getList: "/ticket/list",
      getMessages: "/ticket/thread/",
      sendMessage: "/ticket/comment",
      closeTicket: "/ticket/close/",
      createTicket: "/ticket/create",
    },
    user: {
      updateProfile: "user/update-profile",
      changePassword: "user/change-password",
      updateBankAccount: "/user/bank-account",
      bankDetails: "/user/bank-details",
    },
    quiz: {
      create: "/book/quiz/create",
      update: "/book/quiz/update",
      delete: "/book/quiz/delete/",
      getQuiz: "/book/quiz/",
      getQuizByBook: "/book/quiz/book/",
    },
    question: {
      add: "/book/quiz/question/add",
      update: "/book/quiz/question/update",
      delete: "/book/quiz/question/delete/",
      getQuestion: "/book/quiz/question/",
      publish: "/book/quiz/publish/",
    },
    mou: {
      get: "/mou/list/",
      sign: "/mou/sign",
      decline: "/mou/decline/",
    },
    book: {
      allBook: "/book/all",
      bookDetail: "/book/",
      bookPreviewAll: "/book/pages/",
      deleteBook: "/book/delete",
      addBook: "/book/add",
      updateBook: "/book/edit",
      uploadBook: "/book/upload",
      genreList: "genres/list",
      tagList: "tags/list",
      languateList: "languages/list",
      ageRange: "age-ranges/list",
      submitRevision: "/book/revision/submit",
      revisions: "/book/revision/history/",
      bookStats: "/book/stats",
      singleBookStats: "/book/:id/stats",
    },
    order: {
      list: "/order/list",
      stats: "/order/stats",
      detail: "/order/details",
      cancel: "/order/cancel",
      updateStatus: "/order/update-Status",
    },
    feature: {
      getPublishedBooks: "/book/published",
      getRecentCovers: "/book/feature/recent-covers",
      request: "/book/feature/request",
      getList: "/book/feature/list",
      stats: "/book/feature/stats",
      cancel: "/book/feature/cancel",
      featuredBooks: "books/list/featured",
    },
    wallet: {
      payments: "/wallet/payments",
      userSpendings: "/wallet/user-spendings",
      stats: "/wallet/stats",
      bookSales: "/wallet/book-sales/",
    },
    authors: {
      create: "/partner-author/create",
      list: "/partner-author/list",
      update: "/partner-author/update",
      activate: "/partner-author/activate/",
      deActivate: "/partner-author/deactivate/",
      profile: "/partner-author/profile/",
      books: "/partner-author/",
      payments: "/partner-author/:id/payments",
      bookSales: "/partner-author/:id/payments/:payment_id/sales",
      sendPayment: "/partner-author/upload-receipt",
    },
  },
  kid: {
    book: {
      getBook: "books/",
      all: "books/list/all",
      bookFavorite: "books/favourite/add",
      removeFavourite: "books/favourite/remove",
      bookPreview: "books/pages/",
      trackBook: "/books/track/progress",
      bookFavList: "books/favourite/list",
      suggestion: "books/list/suggestions",
      bookReviewList: "books/rating/list",
      addRating: "books/rating/add",
      ratingStats: "books/rating/stats",
      myBooks: "user/books/list",
      buy: "books/access/buy",
      finishBook: "books/track/status/",
      progress: "user/books/progress",
      listFewBooks: "books/list/few",
      newArrival: "books/list/new-arrivals",
      access: "books/access",
      hardCopySuggestion: "books/list/hard-copy-suggestions",
      sharedBooks: "user/books/shared",
      markAsRead: "user/books/mark-assigned-book-viewed/",
    },
    cart: {
      add: "cart/add",
      list: "cart/list",
      changeQuantity: "cart/quantity/",
      remove: "cart/remove/",
      count: "cart/count",
      checkout: "order/checkout",
      orderList: "order/list",
      cancelOrder: "order/cancel",
    },
    publisher: {
      list: "publishers/list",
      profile: "publishers/profile/",
      associatedPartner: "publishers/partner-authors/",
    },
    author: {
      profile: "authors/profile/",
    },
    user: {
      profile: "user/profile",
      updateAddress: "user/update-address",
      getAddress: "user/address",
      getAchievements: "user/achievements",
    },
    quiz: {
      startQuiz: "books/quiz/start/",
      getQuestion: "books/quiz/questions/",
      quizAttempt: "books/quiz/attempt",
      result: "books/quiz/result/",
    },
    wallet: {
      wallet: "user/wallet",
      history: "user/wallet/history",
    },
    report: {
      list: "report/reasons/list",
      report: "report/request",
    },
    feedback: {
      feedback: "feedback/list",
    },
    plans: {
      buy: "subscription/buy",
      activePlan: "subscription/active",
      buyCoins: "subscription/buy/coins",
      history: "subscription/history",
      transactionHistory: "subscription/transactions/list",
      topUps: "plans/list/topup",
      topUpsHistory: "subscription/topup/history/",
      uploadTransactionSlip: "subscription/transactions/upload-receipt",
    },
    leadershipBoard: {
      getStats: "user/leadership-board",
    },
    badges: {
      listAll: "badges/list",
    },
    share: {
      getShareInfo: "badge/share/",
    },
  },
  parent: {
    dashboard: {
      getKids: "kids/list",
      addKid: "kids/add",
      activateKid: "kids/activate/",
      deActivateKid: "kids/deactivate/",
      getStats: "stats/parent/dashboarad",
      assignCoins: "kids/assign-coins",
    },
    kids: {
      profile: "kids/profile/",
      progress: "kids/books-progress/",
      update: "kids/update",
      badges: "kids/level-achievements/",
      unAssign: "kids/unassign-book",
      assign: "kids/assign-book",
      assigneelist: "kids/kids-list-to-assign-book/",
      ageRangelist: "kids/age-ranges",
    },
  },
  general: {
    privacy: "pages/privacy-policy",
    terms: "pages/terms-and-conditions",
    newsLetter: "newsletter/subscribe",
    plans: "plans/list",
    authors: "authors/list",
    authorProfile: "authors/profile/",
    publicPreview: "books/pages/",
  },
};

export { BaseURL, Endpoint, FacebookAppId, GoogleAPI, ProxyURL };
